/**
 * Kindergarten API
 * This is the API for Kindergarten
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@kindergarten.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GroupgroupIdcreatePostPoll {
  
  @SerializedName("question")
  private String question = null;
  @SerializedName("answers")
  private List<String> answers = null;

  /**
   * the question of the poll
   **/
  @ApiModelProperty(value = "the question of the poll")
  public String getQuestion() {
    return question;
  }
  public void setQuestion(String question) {
    this.question = question;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getAnswers() {
    return answers;
  }
  public void setAnswers(List<String> answers) {
    this.answers = answers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupgroupIdcreatePostPoll groupgroupIdcreatePostPoll = (GroupgroupIdcreatePostPoll) o;
    return (this.question == null ? groupgroupIdcreatePostPoll.question == null : this.question.equals(groupgroupIdcreatePostPoll.question)) &&
        (this.answers == null ? groupgroupIdcreatePostPoll.answers == null : this.answers.equals(groupgroupIdcreatePostPoll.answers));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.question == null ? 0: this.question.hashCode());
    result = 31 * result + (this.answers == null ? 0: this.answers.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupgroupIdcreatePostPoll {\n");
    
    sb.append("  question: ").append(question).append("\n");
    sb.append("  answers: ").append(answers).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
