/**
 * Kindergarten API
 * This is the API for Kindergarten
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@kindergarten.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GroupgroupIdcreatePostPath {
  
  @SerializedName("x")
  private BigDecimal x = null;
  @SerializedName("y")
  private BigDecimal y = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getX() {
    return x;
  }
  public void setX(double x) {
    this.x = x;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getY() {
    return y;
  }
  public void setY(double y) {
    this.y = y;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupgroupIdcreatePostPath groupgroupIdcreatePostPath = (GroupgroupIdcreatePostPath) o;
    return (this.x == null ? groupgroupIdcreatePostPath.x == null : this.x.equals(groupgroupIdcreatePostPath.x)) &&
        (this.y == null ? groupgroupIdcreatePostPath.y == null : this.y.equals(groupgroupIdcreatePostPath.y));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.x == null ? 0: this.x.hashCode());
    result = 31 * result + (this.y == null ? 0: this.y.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupgroupIdcreatePostPath {\n");
    
    sb.append("  x: ").append(x).append("\n");
    sb.append("  y: ").append(y).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
