/**
 * Kindergarten API
 * This is the API for Kindergarten
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@kindergarten.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.Vote;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class KindergartenPoll {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("question")
  private String question = null;
  @SerializedName("options")
  private List<String> options = null;
  @SerializedName("votes")
  private List<Vote> votes = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getQuestion() {
    return question;
  }
  public void setQuestion(String question) {
    this.question = question;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getOptions() {
    return options;
  }
  public void setOptions(List<String> options) {
    this.options = options;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<Vote> getVotes() {
    return votes;
  }
  public void setVotes(List<Vote> votes) {
    this.votes = votes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KindergartenPoll kindergartenPoll = (KindergartenPoll) o;
    return (this.id == null ? kindergartenPoll.id == null : this.id.equals(kindergartenPoll.id)) &&
        (this.question == null ? kindergartenPoll.question == null : this.question.equals(kindergartenPoll.question)) &&
        (this.options == null ? kindergartenPoll.options == null : this.options.equals(kindergartenPoll.options)) &&
        (this.votes == null ? kindergartenPoll.votes == null : this.votes.equals(kindergartenPoll.votes));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.question == null ? 0: this.question.hashCode());
    result = 31 * result + (this.options == null ? 0: this.options.hashCode());
    result = 31 * result + (this.votes == null ? 0: this.votes.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class KindergartenPoll {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  question: ").append(question).append("\n");
    sb.append("  options: ").append(options).append("\n");
    sb.append("  votes: ").append(votes).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
