/**
 * Kindergarten API
 * This is the API for Kindergarten
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.Comment;
import io.swagger.client.model.Image;
import io.swagger.client.model.Like;
import io.swagger.client.model.Poll;
import io.swagger.client.model.User;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Post {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("creator")
  private User creator = null;
  @SerializedName("content")
  private String content = null;
  @SerializedName("image")
  private Image image = null;
  @SerializedName("poll")
  private Poll poll = null;
  @SerializedName("likes")
  private List<Like> likes = null;
  @SerializedName("comments")
  private List<Comment> comments = null;
  @SerializedName("creationDate")
  private String creationDate = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public User getCreator() {
    return creator;
  }
  public void setCreator(User creator) {
    this.creator = creator;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getContent() {
    return content;
  }
  public void setContent(String content) {
    this.content = content;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Image getImage() {
    return image;
  }
  public void setImage(Image image) {
    this.image = image;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Poll getPoll() {
    return poll;
  }
  public void setPoll(Poll poll) {
    this.poll = poll;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<Like> getLikes() {
    return likes;
  }
  public void setLikes(List<Like> likes) {
    this.likes = likes;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<Comment> getComments() {
    return comments;
  }
  public void setComments(List<Comment> comments) {
    this.comments = comments;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getCreationDate() {
    return creationDate;
  }
  public void setCreationDate(String creationDate) {
    this.creationDate = creationDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Post post = (Post) o;
    return (this.id == null ? post.id == null : this.id.equals(post.id)) &&
        (this.creator == null ? post.creator == null : this.creator.equals(post.creator)) &&
        (this.content == null ? post.content == null : this.content.equals(post.content)) &&
        (this.image == null ? post.image == null : this.image.equals(post.image)) &&
        (this.poll == null ? post.poll == null : this.poll.equals(post.poll)) &&
        (this.likes == null ? post.likes == null : this.likes.equals(post.likes)) &&
        (this.comments == null ? post.comments == null : this.comments.equals(post.comments)) &&
        (this.creationDate == null ? post.creationDate == null : this.creationDate.equals(post.creationDate));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.creator == null ? 0: this.creator.hashCode());
    result = 31 * result + (this.content == null ? 0: this.content.hashCode());
    result = 31 * result + (this.image == null ? 0: this.image.hashCode());
    result = 31 * result + (this.poll == null ? 0: this.poll.hashCode());
    result = 31 * result + (this.likes == null ? 0: this.likes.hashCode());
    result = 31 * result + (this.comments == null ? 0: this.comments.hashCode());
    result = 31 * result + (this.creationDate == null ? 0: this.creationDate.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Post {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  creator: ").append(creator).append("\n");
    sb.append("  content: ").append(content).append("\n");
    sb.append("  image: ").append(image).append("\n");
    sb.append("  poll: ").append(poll).append("\n");
    sb.append("  likes: ").append(likes).append("\n");
    sb.append("  comments: ").append(comments).append("\n");
    sb.append("  creationDate: ").append(creationDate).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
