/**
 * Kindergarten API
 * This is the API for Kindergarten
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Presence {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("wasThere")
  private Boolean wasThere = null;
  @SerializedName("date")
  private String date = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getWasThere() {
    return wasThere;
  }
  public void setWasThere(Boolean wasThere) {
    this.wasThere = wasThere;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDate() {
    return date;
  }
  public void setDate(String date) {
    this.date = date;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Presence presence = (Presence) o;
    return (this.id == null ? presence.id == null : this.id.equals(presence.id)) &&
        (this.wasThere == null ? presence.wasThere == null : this.wasThere.equals(presence.wasThere)) &&
        (this.date == null ? presence.date == null : this.date.equals(presence.date));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.wasThere == null ? 0: this.wasThere.hashCode());
    result = 31 * result + (this.date == null ? 0: this.date.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Presence {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  wasThere: ").append(wasThere).append("\n");
    sb.append("  date: ").append(date).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
